# Generated by Django 5.0.2 on 2024-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameproject', models.CharField(max_length=200)),
                ('Streetaddress', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=700)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops_images/')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
    ]
